import configs.base as cfg


def test_factor_lab_stageA2_cmom_config_exists() -> None:
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_LOOKBACK_DAYS == 14
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_SKIP_RECENT_DAYS == 1
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MIN_RETURN_DIFF_PCT == 10.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MAX_BTC_UNDERPERFORMANCE_PCT == 10.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MAX_ETH_UNDERPERFORMANCE_PCT == 10.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MIN_REBALANCE_COUNT == cfg.FACTOR_LAB_STAGEA_MIN_REBALANCE_COUNT
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MIN_EW_IMPROVEMENT_DIFF_PCT == 5.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MAX_3D_DIAGNOSTIC_DRAWDOWN_WORSENING_PCT == 5.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MAX_3D_DIAGNOSTIC_TOP5_UNDERPERFORMANCE_PCT == 10.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MAX_3D_DIAGNOSTIC_MONTH_SHARE == 0.50
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MIN_PROCEED_TOTAL_RETURN_PCT == -50.0
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_MIN_PROCEED_STRESS_50BPS_RETURN_PCT == -60.0


def test_factor_lab_stageA2_cmom_keeps_live_disabled() -> None:
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_LIVE_SAFE is False
    assert cfg.FACTOR_LAB_STAGEA2_CMOM_PAPER_SHADOW_ALLOWED is False
