from configs import base


def test_extreme_funding_phase1a_config_constants_exist():
    assert base.EXTREME_FUNDING_WATCH_SYMBOLS == (
        "XRP/USDT",
        "DOGE/USDT",
        "ADA/USDT",
        "ETH/USDT",
        "SOL/USDT",
        "BTC/USDT",
    )
    assert base.EXTREME_FUNDING_PRE_SIGNAL_ANNUALIZED_THRESHOLD_PCT == 30.0
    assert base.EXTREME_FUNDING_STRONG_PRE_SIGNAL_ANNUALIZED_THRESHOLD_PCT == 50.0
    assert base.EXTREME_FUNDING_TRADE_SIGNAL_ANNUALIZED_THRESHOLD_PCT == 100.0
    assert base.EXTREME_FUNDING_MICRO_PERSISTENCE_WINDOW_MIN == 30
    assert base.EXTREME_FUNDING_MICRO_PERSISTENCE_MIN == 0.70
    assert base.EXTREME_FUNDING_MICRO_PERSISTENCE_MIN_WEAK == 0.50
    assert base.EXTREME_FUNDING_OI_CONFIRMATION_MIN_CHANGE_1H_PCT == 0.0
    assert base.EXTREME_FUNDING_OI_STRONG_CONFIRMATION_MIN_CHANGE_1H_PCT == 3.0
    assert base.EXTREME_FUNDING_MARK_DATA_POLL_INTERVAL_SEC == 10
    assert base.EXTREME_FUNDING_OI_POLL_INTERVAL_SEC == 60
    assert base.EXTREME_FUNDING_KLINE_REFRESH_INTERVAL_SEC == 3600
    assert base.EXTREME_FUNDING_HEARTBEAT_INTERVAL_SEC == 300
    assert base.EXTREME_FUNDING_MAX_MARK_DATA_AGE_SEC == 30
    assert base.EXTREME_FUNDING_MAX_OI_DATA_AGE_SEC == 180
