"""
tests/research/external_signal_shadow/stage1_4a2_vendor_fixtures.py
"""

def base_vendor_audit_payload() -> dict:
    return {
        "vendor": "tardis_dev",
        "priority": "P1",
        "source_surface": "trial_export",
        "evidence_level": "trial_export",
        "evidence_urls": ["https://docs.tardis.dev/"],
        "evidence_retrieved_at": "2026-06-15",
        "audit_time_ms": 1781452800000,
        "sample_access_type": "free_trial",
        "payment_required_before_sample": False,
        "sales_contact_required": False,
        "api_key_required_for_sample": False,
        "sample_file_available": True,
        "sample_file_path": "data/external_signal_shadow/vendor_liquidation_samples/tardis_dev/sample.jsonl",
        "sample_file_audited": True,
        "sample_audit_row_count": 100,
        "sample_audit_history_days": 120.0,
        "explicit_user_approval_for_trial": False,
        "explicit_user_approval_for_paid_sample": False,
        "explicit_user_cost_approval": False,
        "license_status": "clear",
        "license_allows_local_research": True,
        "license_allows_backtesting": True,
        "license_allows_local_storage": True,
        "license_allows_derived_metrics": True,
        "redistribution_forbidden": True,
        "history_days_claimed": 180.0,
        "history_days_verified_from_sample": 120.0,
        "symbols_claimed": ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
        "symbols_verified": ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
        "exchange_scope": "binance_usdm",
        "binance_usdm_exact": True,
        "includes_coin_margined": False,
        "includes_usd_margined": True,
        "multi_exchange_aggregate": False,
        "exchange_filter_available": True,
        "timestamp_resolution_ms": 60_000,
        "side_available": True,
        "side_semantics": "long_short",
        "long_liquidation_mapping": "long_liquidation_usd",
        "short_liquidation_mapping": "short_liquidation_usd",
        "side_mapping_confidence": "verified",
        "notional_usd_available": True,
        "price_available": False,
        "quantity_available": False,
        "exchange_field_available": True,
        "symbol_field_available": True,
        "timestamp_field_available": True,
        "download_or_export_format": "jsonl",
        "source_granularity": "1m",
        "replay_anchor_policy": "bucket_end_plus_lag",
        "available_at_policy_defined": True,
        "field_mapping_status": "compatible",
        "stage1_4a1_alignment_status": "compatible",
        "cost_tier": "low",
        "personal_investor_feasible_cost": True,
        "estimated_cost_usd_per_month": 49.0,
        "manual_notes": [],
    }
