from configs import base


def test_stage1_4e_deleveraging_proxy_config_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_PRICE_RETURN_THRESHOLD == 0.02
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_OI_DROP_THRESHOLD == -0.03
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_PRICE_RETURN_THRESHOLD == 0.03
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_OI_DROP_THRESHOLD == -0.05

    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_CONFIGURED_DATA_LAG_MS == 300_000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_COOLDOWN_MS == 3_600_000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_COOLDOWN_MS == 14_400_000

    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_MAX_OI_MEDIAN_INTERVAL_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_MAX_OI_P95_INTERVAL_MS == 30 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_MAX_OI_MEDIAN_INTERVAL_MS == 60 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_MAX_OI_P95_INTERVAL_MS == 2 * 60 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_MAX_PRICE_MEDIAN_INTERVAL_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_15M_MAX_PRICE_P95_INTERVAL_MS == 30 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_MAX_PRICE_MEDIAN_INTERVAL_MS <= 60 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_1H_MAX_PRICE_P95_INTERVAL_MS <= 2 * 60 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MAX_OI_STALENESS_MS > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MAX_PRICE_STALENESS_MS > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MIN_RESEARCH_RESULT_HISTORY_DAYS >= 30

    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_FORWARD_WINDOWS_HOURS == (1, 4, 12)
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_COST_SCENARIOS_BPS == (30, 50, 80)
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_PRIMARY_COST_BPS == 50
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_RANDOM_BASELINE_TRIALS >= 500
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_LEFT_TAIL_PERCENTILE == 5

    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MIN_PASS_EVENT_COUNT == 100
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MIN_PASS_EVENT_DAYS == 20
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MIN_SPARSE_EVENT_COUNT == 30
    assert base.EXTERNAL_SIGNAL_STAGE1_4E_DELEVERAGING_PROXY_MIN_SPARSE_EVENT_DAYS == 10
