from __future__ import annotations

from configs import base


def test_stage1_3_config_constants_are_registered() -> None:
    assert base.EXTERNAL_SIGNAL_STAGE1_3_VOLUME_SPIKE_THRESHOLD == 3.0
    assert base.EXTERNAL_SIGNAL_STAGE1_3_REL_STRENGTH_Z_THRESHOLD == 1.5
    assert base.EXTERNAL_SIGNAL_STAGE1_3_ROLLING_DAYS == 7
    assert base.EXTERNAL_SIGNAL_STAGE1_3_SAME_HOUR_MIN_SAMPLES == 5
    assert base.EXTERNAL_SIGNAL_STAGE1_3_ROLLING_STD_MIN_SAMPLES == 48
    assert base.EXTERNAL_SIGNAL_STAGE1_3_SNAPSHOT_INTERVAL_MINUTES == 15
    assert base.EXTERNAL_SIGNAL_STAGE1_3_ONE_HOUR_BAR_COUNT == 4
    assert base.EXTERNAL_SIGNAL_STAGE1_3_FORWARD_4H_BAR_COUNT == 16
    assert base.EXTERNAL_SIGNAL_STAGE1_3_HISTORY_DAYS_PREFERRED == 180
    assert base.EXTERNAL_SIGNAL_STAGE1_3_HISTORY_DAYS_MIN == 90
    assert base.EXTERNAL_SIGNAL_STAGE1_3_CONFIGURED_DATA_LAG_MS == 60_000
    assert base.EXTERNAL_SIGNAL_STAGE1_3_ENTRY_DELAY_BARS == 1
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MIN_EVENT_COUNT == 100
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MIN_EVENT_DAYS == 20
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MIN_SYMBOLS_WITH_EVENTS == 3
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MAX_SINGLE_SYMBOL_EVENT_SHARE == 0.50
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MAX_SINGLE_DAY_EVENT_SHARE == 0.20
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MAX_TOP5_POSITIVE_PNL_SHARE == 0.30
    assert base.EXTERNAL_SIGNAL_STAGE1_3_RANDOM_BASELINE_TRIALS == 500
    assert base.EXTERNAL_SIGNAL_STAGE1_3_RANDOM_SEED == 20260613
    assert base.EXTERNAL_SIGNAL_STAGE1_3_COST_SCENARIOS_ROUND_TRIP_BPS == (30.0, 50.0, 80.0)
    assert base.EXTERNAL_SIGNAL_STAGE1_3_MIN_BAR_COVERAGE_RATIO == 0.98
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_BASE_URL == "https://data-api.binance.vision"
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_KLINES_PATH == "/api/v3/klines"
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_SYMBOLS == ("BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT")
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_INTERVAL == "15m"
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_KLINES_LIMIT == 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_TIMEOUT_SEC == 10.0
    assert base.EXTERNAL_SIGNAL_STAGE1_3_BINANCE_PROXY_REQUEST_SLEEP_SEC == 0.2


def test_stage1_3_runtime_boundaries_are_disabled() -> None:
    assert base.RISK_LIVE_TRADING_ENABLED is False
