from configs import base


def test_stage1_5g_config_constants_exist_and_are_observation_only():
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_SCHEMA_VERSION == 1
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_REQUEST_SUCCESS_RATE == 0.98
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_PER_SYMBOL_REQUEST_SUCCESS_RATE == 0.98
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_SNAPSHOT_COVERAGE_RATIO == 0.95
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_SLIPPAGE_TEST_NOTIONAL_USDT == 500.0
    assert base.RISK_LIVE_TRADING_ENABLED is False


def test_stage1_5g_thresholds_are_safe_ranges():
    assert 0.0 < base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_HEALTHY_WINDOW_RATIO <= 1.0
    assert 0.0 <= base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_NULL_RATIO < 0.05
    assert 0.0 <= base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_DUPLICATE_SNAPSHOT_RATIO < 0.10
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_EVENT_FAMILY_SAMPLE_REQUIRED >= 3
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_SOURCE_ARTICLES_REQUIRED >= 2
