from configs import base


def test_stage1_5c1_config_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_BINANCE_FAPI_BASE_URL == "https://fapi.binance.com"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_BINANCE_SPOT_BASE_URL == "https://api.binance.com"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_FUTURES_EXCHANGE_INFO_PATH == "/fapi/v1/exchangeInfo"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_FUTURES_KLINES_PATH == "/fapi/v1/klines"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_SPOT_EXCHANGE_INFO_PATH == "/api/v3/exchangeInfo"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_SPOT_KLINES_PATH == "/api/v3/klines"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_KLINE_INTERVAL == "15m"
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_KLINE_INTERVAL_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_KLINE_LIMIT == 1500
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_ALLOWED_FUTURES_QUOTE_ASSETS == ("USDT", "USDC")
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_TIMEOUT_SEC == 10.0
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_REQUEST_SLEEP_SEC == 0.2
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_RETRY_BUDGET == 2
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MAX_KLINE_REQUESTS_PER_RUN == 500
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MAX_SYMBOLS_PER_RUN == 250
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_PRE_EVENT_HISTORY_DAYS == 30
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_POST_EVENT_BUFFER_DAYS == 2
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MERGE_GAP_MS == 6 * 60 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MIN_RERUN_EVENT_COUNT == 30
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MIN_RERUN_EVENT_DAYS == 10
    assert base.EXTERNAL_SIGNAL_STAGE1_5C1_MIN_RERUN_SYMBOLS == 3
