from configs import base


def test_stage1_5d_config_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_BINANCE_ANNOUNCEMENT_BASE_URL == "https://www.binance.com"
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_BINANCE_ANNOUNCEMENT_LIST_PATH
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_ANNOUNCEMENT_QUERY_PARAMS == {
        "type": "1",
        "pageNo": "1",
        "pageSize": "50",
    }
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_ALLOWED_DOMAINS == ("binance.com", "www.binance.com")
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_PRIMARY_EVENT_TYPE == "futures_contract_launch"
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_PRIMARY_ANNOUNCEMENT_DELAY_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_DEFAULT_POLL_INTERVAL_SEC == 60
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_REQUEST_TIMEOUT_SEC == 10.0
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_RETRY_BUDGET == 2
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_MIN_OPERATIONAL_OBSERVATION_HOURS == 24
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_MIN_POLL_SUCCESS_RATE == 0.95
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_FIRST_BAR_OBSERVATION_TIMEOUT_HOURS == 24
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_FIRST_BAR_CHECK_BUDGET_PER_POLL >= 1
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_RAW_PAYLOAD_RETENTION_DAYS >= 14
    assert base.EXTERNAL_SIGNAL_STAGE1_5D_MAX_RAW_PAYLOAD_BYTES_PER_DAY > 0
