from configs import base


def test_stage1_4b_lite_threshold_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_EVENT_DETECTION_WINDOW_HOURS == 4
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_ENTRY_DELAY_BARS == 1
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_PRIMARY_FORWARD_WINDOW_HOURS == 4
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_SECONDARY_FORWARD_WINDOWS_HOURS == (1, 12)

    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_FUNDING_EXTREME_PERCENTILE == 90
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_FUNDING_PERCENTILE_LOOKBACK_DAYS == 90
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MIN_FUNDING_HISTORY_POINTS == 30
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_OI_EXPANSION_4H_PCT == 0.02
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_OI_CONTRACTION_4H_PCT == -0.02
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_PRICE_RETURN_4H_PCT == 0.015
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_PRICE_FLUSH_4H_PCT == 0.02
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_PRICE_BASELINE_1H_RETURN_PCT == 0.015

    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_FUNDING_PUBLISH_LAG_MS == base.EXTERNAL_SIGNAL_STAGE1_4_FUNDING_PUBLISH_LAG_MS
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MAX_OI_STALENESS_MS > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MIN_OI_HISTORY_POINTS >= 2
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_EVENT_COOLDOWN_HOURS == 4

    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_RANDOM_BASELINE_TRIALS >= 500
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_COST_SCENARIOS_BPS == (30, 50, 80)
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MIN_EVENT_COUNT == 100
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MIN_EVENT_DAYS == 20
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MIN_SYMBOLS_WITH_EVENTS == 3
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MAX_SINGLE_SYMBOL_EVENT_SHARE == 0.50
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MAX_SINGLE_DAY_EVENT_SHARE == 0.20
    assert base.EXTERNAL_SIGNAL_STAGE1_4B_LITE_MAX_TOP5_POSITIVE_GROSS_PROFIT_SHARE == 0.30
