"""
tests/research/external_signal_shadow/test_stage1_4a_config.py
"""

from configs.base import (
    EXTERNAL_SIGNAL_STAGE1_4_BAR_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_FUNDING_FIELD_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_FUNDING_SETTLEMENT_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_HISTORY_DAYS_MIN,
    EXTERNAL_SIGNAL_STAGE1_4_HISTORY_DAYS_PREFERRED,
    EXTERNAL_SIGNAL_STAGE1_4_LIQUIDATION_FIELD_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_LIQUIDATION_TIME_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_MIN_USABLE_SYMBOLS,
    EXTERNAL_SIGNAL_STAGE1_4_OI_FIELD_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_OI_TIME_COVERAGE_MIN_RATIO,
    EXTERNAL_SIGNAL_STAGE1_4_SYMBOLS,
    RISK_LIVE_TRADING_ENABLED,
)


def test_stage1_4a_constants():
    assert len(EXTERNAL_SIGNAL_STAGE1_4_SYMBOLS) == 5
    assert "BTCUSDT" in EXTERNAL_SIGNAL_STAGE1_4_SYMBOLS
    assert EXTERNAL_SIGNAL_STAGE1_4_HISTORY_DAYS_PREFERRED == 180
    assert EXTERNAL_SIGNAL_STAGE1_4_HISTORY_DAYS_MIN == 90
    assert EXTERNAL_SIGNAL_STAGE1_4_MIN_USABLE_SYMBOLS == 3

    assert EXTERNAL_SIGNAL_STAGE1_4_BAR_COVERAGE_MIN_RATIO == 0.95
    assert EXTERNAL_SIGNAL_STAGE1_4_LIQUIDATION_FIELD_COVERAGE_MIN_RATIO == 0.90
    assert EXTERNAL_SIGNAL_STAGE1_4_LIQUIDATION_TIME_COVERAGE_MIN_RATIO == 0.90
    assert EXTERNAL_SIGNAL_STAGE1_4_FUNDING_FIELD_COVERAGE_MIN_RATIO == 0.95
    assert EXTERNAL_SIGNAL_STAGE1_4_FUNDING_SETTLEMENT_COVERAGE_MIN_RATIO == 0.95
    assert EXTERNAL_SIGNAL_STAGE1_4_OI_FIELD_COVERAGE_MIN_RATIO == 0.90
    assert EXTERNAL_SIGNAL_STAGE1_4_OI_TIME_COVERAGE_MIN_RATIO == 0.90


def test_safety_master_switch():
    # L0 Safety Rule: RISK_LIVE_TRADING_ENABLED must be False by default.
    assert RISK_LIVE_TRADING_ENABLED is False


def test_stage1_4a1_binance_vision_metrics_config_exists():
    from configs import base

    assert base.EXTERNAL_SIGNAL_STAGE1_4_BINANCE_VISION_METRICS_DAILY_PATH_TEMPLATE == (
        "/data/futures/um/daily/metrics/{symbol}/{symbol}-metrics-{date}.zip"
    )
    assert base.EXTERNAL_SIGNAL_STAGE1_4_BINANCE_VISION_OI_OUTPUT_JSONL.endswith(".jsonl")
    assert base.EXTERNAL_SIGNAL_STAGE1_4_PUBLIC_REST_PAGE_LIMIT > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4_PUBLIC_REST_PAGE_LIMIT <= 1500

