from configs import base


def test_stage1_5g_config_constants_exist_and_are_observation_only():
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_SCHEMA_VERSION == 2
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_REQUEST_SUCCESS_RATE == 0.98

    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_PER_SYMBOL_REQUEST_SUCCESS_RATE == 0.98
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_SNAPSHOT_COVERAGE_RATIO == 0.95
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_SLIPPAGE_TEST_NOTIONAL_USDT == 500.0
    assert base.RISK_LIVE_TRADING_ENABLED is False


def test_stage1_5g_thresholds_are_safe_ranges():
    assert 0.0 < base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_HEALTHY_WINDOW_RATIO <= 1.0
    assert 0.0 <= base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_NULL_RATIO < 0.05
    assert 0.0 <= base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_DUPLICATE_SNAPSHOT_RATIO < 0.10
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_EVENT_FAMILY_SAMPLE_REQUIRED >= 3
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_SOURCE_ARTICLES_REQUIRED >= 2


def test_stage1_5g_quarantine_config_constants_exist_and_are_safe():
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_INVALID_BOOK_RATIO == 0.02
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_LAUNCH_WARMUP_WINDOW_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_LAUNCH_WARMUP_INVALID_ROW_COUNT == 15
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_LAUNCH_WARMUP_INVALID_MINUTE_BUCKET_COUNT == 12
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_MIDRUN_INVALID_BOOK_RATIO == 0.002
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_MIDRUN_INVALID_BOOK_COUNT == 1
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_CONSECUTIVE_INVALID_AFTER_WARMUP == 1
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_VALID_SNAPSHOTS_AFTER_QUARANTINE == 684
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MIN_BOOK_AVAILABILITY_RATIO == 0.98
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_MAX_FIRST_VALID_BOOK_LATENCY_MS == 15 * 60 * 1000
    assert base.EXTERNAL_SIGNAL_STAGE1_5G_CROSSED_OR_NEGATIVE_BOOK_ALLOWED is False
