from configs import base


def test_stage1_5a_source_audit_config_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_ALLOWED_DOMAINS
    assert "binance.com" in base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_ALLOWED_DOMAINS
    assert "okx.com" in base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_ALLOWED_DOMAINS

    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_MAX_PAYLOAD_BYTES > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_MAX_JSON_DEPTH >= 4
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_REQUEST_TIMEOUT_SEC > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_RETRY_BUDGET >= 0
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_SOURCE_AUDIT_MAX_EVENTS_PER_PAGE > 0

    assert base.EXTERNAL_SIGNAL_STAGE1_5A_ANNOUNCEMENT_DELAY_SCENARIOS_MS == (
        5 * 60 * 1000,
        15 * 60 * 1000,
        60 * 60 * 1000,
    )
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_PRIMARY_ANNOUNCEMENT_DELAY_MS == 15 * 60 * 1000

    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_HISTORICAL_EVENTS_FOUND == 30
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_PRIMARY_EVENT_TYPE_EVENTS == 20
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_UNIQUE_EVENT_DAYS == 20
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_SYMBOLS_WITH_EVENTS == 3
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_SOURCE_INTEGRITY_PASS_RATE == 0.95
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_TRADE_PAIR_MAPPING_PASS_RATE == 0.95
    assert base.EXTERNAL_SIGNAL_STAGE1_5A_MIN_TIMESTAMP_HIGH_OR_MEDIUM_RATIO == 0.95
    assert set(base.EXTERNAL_SIGNAL_STAGE1_5A_ELIGIBLE_EVENT_TYPES_FOR_STAGE1_5B)
    assert "exchange_delisting_notice" in base.EXTERNAL_SIGNAL_STAGE1_5A_ELIGIBLE_EVENT_TYPES_FOR_STAGE1_5B
    assert "new_coin_listing" in base.EXTERNAL_SIGNAL_STAGE1_5A_OBSERVATION_ONLY_EVENT_TYPES
    assert "whale_deposit" in base.EXTERNAL_SIGNAL_STAGE1_5A_OBSERVATION_ONLY_EVENT_TYPES
