from configs import base


def test_stage1_4a_lq30_threshold_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_HISTORY_DAYS == 15
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_SYMBOLS_WITH_EVENTS == 3
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_EVENT_DAYS == 10
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_ALIGNMENT_OVERLAP_EVENT_DAYS == 10
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_SINGLE_SYMBOL_EVENT_SHARE == 0.60
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_SINGLE_DAY_EVENT_SHARE == 0.35
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_TOP1_DAY_NOTIONAL_SHARE == 0.50
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_TOP3_DAYS_NOTIONAL_SHARE == 0.70
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_TOP1_SYMBOL_NOTIONAL_SHARE == 0.70
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_INVALID_JSON_LINE_RATIO == 0.001


def test_stage1_4a_lq30_bucket_and_alignment_constants_exist():
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_BUCKET_15M_MS == 900_000
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_BUCKET_1H_MS == 3_600_000
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_CONFIGURED_LAG_MS == 60_000
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_FUNDING_PUBLISH_LAG_MS > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MAX_OI_STALENESS_MS > 0
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_ABS_FUNDING_RATE_PREVIEW >= 0.0
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_ABS_OI_CHANGE_RATIO_PREVIEW >= 0.0
    assert base.EXTERNAL_SIGNAL_STAGE1_4_LQ30_MIN_ABS_PRICE_RETURN_1H_PREVIEW >= 0.0
